name: Build Platform Binaries

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'
    - run: go version

    - name: Use LTS Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Build
      run: ./build.sh
