# This is a basic workflow to help you get started with Actions

name: Create New Release and Upload Binaries

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.0"
      - run: go version
    
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build
        run: ./build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          name: Release ${{ github.ref }}
          files: |
            ./build/*